name: ros2
services:
  ros2:
    build:
      context: .
      args:
        USERNAME: user
    image: dit/ros2_tutorial:latest
    container_name: ros2_tutorial
    stdin_open: true
    tty: true
    privileged: true
    stop_grace_period: 1s

    network_mode: host
    working_dir: /home/user/ros2_ws
    environment:
      - DISPLAY=$DISPLAY
      - XAUTHORITY=/root/.Xauthority
      - ROS_WS=/home/user/tutorial_ws
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      # Mount X11 server
      - /d/.Xauthority:/root/.Xauthority
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      # Direct Rendering Infrastructure
      - /dev:/dev
      - ../ros2_ws:/home/user/ros2_ws
    command: bash
