version: '3'
services:
  ros1-tutorial-ws:
    build:
      context: .
      args:
        USERNAME: user
    image: dit/tutorial-ws-noetic:latest
    container_name: tutorial-ws-ros1
    stdin_open: true
    tty: true
    privileged: true

    network_mode: host
    working_dir: /home/user/tutorial_ws
    environment:
      - DISPLAY=host.docker.internal:0.0
      - XAUTHORITY=/root/.Xauthority
      - ROS_WS=/home/user/tutorial_ws
    volumes:
      # Mount local timezone into container. ( Readonly )
      # Reference: https://stackoverflow.com/questions/57607381/how-do-i-change-timezone-in-a-docker-container
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      # Mount X11 server
      - /d/.Xauthority:/root/.Xauthority
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      # Direct Rendering Infrastructure
      - /dev:/dev
      - ../:/home/user/tutorial_ws

    command: /bin/bash
